version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout


      # Install and configure SonarScanner
      - run:
          name: Install SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
            echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> $BASH_ENV
            source $BASH_ENV

      # Perform code analysis with SonarQube
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.host.url=$SONAR_HOST_URL

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
